version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: schooldb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: school-backend
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/schooldb
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
    depends_on:
      - db
    ports:
      - "1209:1209"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: school-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:1209/api/v1

volumes:
  pgdata:
